// One-off generator: rasterizes world-atlas countries into a dot grid for the
// Meridian geography map. Output: src/lib/world-dots.ts
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoContains, geoBounds, geoArea, geoCentroid } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const topo = JSON.parse(readFileSync(require.resolve("world-atlas/countries-110m.json"), "utf8"));
const fc = feature(topo, topo.objects.countries);

const ISO = {
  840: "US", 124: "CA", 484: "MX", 76: "BR", 32: "AR", 152: "CL", 826: "GB", 372: "IE",
  250: "FR", 276: "DE", 528: "NL", 56: "BE", 208: "DK", 756: "CH", 752: "SE", 578: "NO",
  246: "FI", 724: "ES", 380: "IT", 620: "PT", 40: "AT", 616: "PL", 392: "JP", 158: "TW",
  156: "CN", 410: "KR", 356: "IN", 36: "AU", 554: "NZ", 710: "ZA", 682: "SA", 784: "AE",
  360: "ID", 764: "TH", 458: "MY", 376: "IL", 792: "TR", 643: "RU",
};
const CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
const isoList = Object.values(ISO);
const charOf = Object.fromEntries(isoList.map((iso, i) => [iso, CHARS[i]]));

const feats = fc.features
  .filter((f) => f.geometry)
  .map((f) => {
    const [[x0, y0], [x1, y1]] = geoBounds(f);
    return { f, iso: ISO[parseInt(f.id, 10)] ?? null, x0, y0, x1, y1 };
  });

const STEP = 2;
const LAT_TOP = 84;
const LAT_BOTTOM = -58;
const rows = [];
for (let lat = LAT_TOP - STEP / 2; lat > LAT_BOTTOM; lat -= STEP) {
  let row = "";
  for (let lon = -180 + STEP / 2; lon < 180; lon += STEP) {
    let ch = ".";
    for (const g of feats) {
      const inLon = g.x0 <= g.x1 ? lon >= g.x0 && lon <= g.x1 : lon >= g.x0 || lon <= g.x1;
      if (!inLon || lat < g.y0 || lat > g.y1) continue;
      if (geoContains(g.f, [lon, lat])) {
        ch = g.iso ? charOf[g.iso] : "#";
        break;
      }
    }
    row += ch;
  }
  rows.push(row);
}

// Centroid of the largest polygon per country of interest (avoids Alaska/Guiana skew)
const centroids = {};
for (const g of feats) {
  if (!g.iso) continue;
  const geom = g.f.geometry;
  const polys = geom.type === "Polygon" ? [geom.coordinates] : geom.coordinates;
  let best = null;
  let bestArea = -1;
  for (const p of polys) {
    const poly = { type: "Polygon", coordinates: p };
    const a = geoArea(poly);
    if (a > bestArea) { bestArea = a; best = poly; }
  }
  const [clon, clat] = geoCentroid(best);
  centroids[g.iso] = [Math.round(clon * 10) / 10, Math.round(clat * 10) / 10];
}
// Small places that the 110m dataset omits
centroids.SG = [103.8, 1.35];
centroids.HK = [114.2, 22.3];

const codeMap = Object.fromEntries(isoList.map((iso) => [charOf[iso], iso]));
const out = `// AUTO-GENERATED by scripts/gen-world.mjs — do not edit by hand.
// Equirectangular dot grid: ${STEP}° cells from lat ${LAT_TOP} to ${LAT_BOTTOM}, lon -180 to 180.
// '.' = sea, '#' = land (untracked country), letters = tracked country (see DOT_CODES).
export const DOT_STEP = ${STEP};
export const DOT_LAT_TOP = ${LAT_TOP};
export const DOT_ROWS: string[] = ${JSON.stringify(rows, null, 0).replace(/","/g, '",\n  "')};
export const DOT_CODES: Record<string, string> = ${JSON.stringify(codeMap)};
export const COUNTRY_CENTROIDS: Record<string, [number, number]> = ${JSON.stringify(centroids)};
`;
writeFileSync(new URL("../src/lib/world-dots.ts", import.meta.url), out);
const land = rows.join("").replace(/\./g, "").length;
console.log(`rows=${rows.length} cols=${rows[0].length} landDots=${land}`);
console.log(rows.filter((_, i) => i % 3 === 0).map((r) => r.replace(/[^.]/g, "o").replace(/\./g, " ")).join("\n"));
